### PR TITLE
HL-374 | Make some calculation and paysubsidy fields nullable

### PR DESCRIPTION
**Pull request by quyenlq**

### CODE REVIEW

**Review by haavikko — CHANGES_REQUESTED** [review]
The initial values of some Calculation and PaySubsidy fields should also be null, according to the ticket:
Calculation.start_date
Calculation.end_date
PaySubsidy.start_date
PaySubsidy.end_date
Calculation.state_aid_max_percentage

This probably requires change in Calculation.reset and PaySubsidy.reset_pay_subsidies,
and changing state_aid_max_percentage default to None

**Comment by haavikko** [comment]
Also, just realized in the refinement meeting that HelsinkiBenefitCalculator code seems to rely on these fields being non-null, so that needs to be fixed too.

**Comment by quyenlq** [comment]
> Also, just realized in the refinement meeting that HelsinkiBenefitCalculator code seems to rely on these fields being non-null, so that needs to be fixed too.

I updated the PR, changed the calculator logic so it'll not generate calculation row `if calculation.start_date and calculation.end_date is None`. Also added some exception & fallback data if values are null. Actually, I don't really know the use case of nullable start_date and end_date so let me know if this is ok

**Review by haavikko — APPROVED** [review]
Looks good to me! Made some minor changes to tests

**Comment by haavikko** [comment]
Merging on behalf of quyenlq

**Pull request merged**
