### PR TITLE
fix: token expiry based on refresh token expiry

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1563](https://helsinkisolutionoffice.atlassian.net/browse/HL-1563?atlOrigin=eyJpIjoiODljOTRiNjRiOGQzNGU2OThhYzE1N2Y0ZjNmNDA2ZWEiLCJwIjoiaiJ9)

Use the longer expiry date of the refresh token to check if token is expired.
## Additional notes :spiral_notepad:

[HL-1563]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3603.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3603.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3603.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3603.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3603.dev.hel.ninja :laughing::tada::tada::tada:

**Review by JanneJuhola — APPROVED** [review]

**Pull request merged**
