### PR TITLE
fix: In application cloning force origin to be applicant

### PR DESCRIPTION
**Pull request by JanneJuhola**
## Description :sparkles:
Force application origin to be applicant

[hl-1547](https://helsinkisolutionoffice.atlassian.net/browse/HL-1547)
## Issues :bug:
In application cloning it was possible to clone paper application and have new paper application that had problem with full application attachment

### CODE REVIEW

**Review by rikuke — APPROVED** [review]

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3653.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3653.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3653.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3653.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr3653.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3653.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
