### PR TITLE
fix: allow applicant messages for all but cancelled and archived app (HL-860)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

* Add more statuses to be ok'd for messaging
* If archived then no message can be sent by applicant
* Fix/add tests for these cases

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2496.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2496.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2496.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2496.dev.hel.ninja** :rocket::rocket::rocket:

**Review by rikuke — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2496.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
