### PR TITLE
fix: missing parameter for delete request query

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Fix for [HL-1357](https://helsinkisolutionoffice.atlassian.net/browse/HL-1357?atlOrigin=eyJpIjoiNGI1NjZjOWFmOWU4NGU2ODllZmI0MzVlMzBkZGU4NWQiLCJwIjoiaiJ9)

Sentry issue:
https://sentry.test.hel.ninja/organizations/city-of-helsinki/issues/12930/events/5fcb1ae01e6a4823b501319dbfa95b78/
## Additional notes :spiral_notepad:

[HL-1357]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3073.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3073.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3073.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3073.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3073.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
