### PR TITLE
HL-849 | Fix insufficient user permissions causing handler application to freeze

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Fix issue with wrong user role. If user is logged and has wrong permissions, log the user out.

# Testing

* On local dev: You must set `NEXT_PUBLIC_MOCK_FLAG=0` (or modify DB for `is_staff=false` on currently logged user) and log in as applicant ([https://localhost:3000](https://localhost:3000)). Then go to [https://localhost:3100](https://localhost:3100).
* On dev/test server: log in as applicant, then go to handler. Loaders spin and nothing gets loaded as all the requests will fail continously.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2158.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2158.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr2158.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2158.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://handler-pr2158.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-pr2158.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://youth-pr2158.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mjturt — APPROVED** [review]

**Pull request merged**
