### PR TITLE
fix: modified_at date for ahjo update request

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1508](https://helsinkisolutionoffice.atlassian.net/browse/HL-1508)
The application's modified_at date is the date that needs to be in the ahjo JSON title when the request is an update or adding of new record request.
Also the title generating function was a bit of an if/else mess, it was refactored to a class based solution with robust comments 😬 and tests.

## Additional notes :spiral_notepad:

[HL-1508]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3452.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3452.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3452.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3452.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3452.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
