### PR TITLE
feat: don't create new status on retry, save error

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1514](https://helsinkisolutionoffice.atlassian.net/browse/HL-1514)
Do not create a new ahjoStatus every time a request to ahjo is attempted, but update the last one.

[HL-1515](https://helsinkisolutionoffice.atlassian.net/browse/HL-1515?atlOrigin=eyJpIjoiZmYzYWRiY2ExYTVmNGRkYTlhMmQxNWQwNGFlOTQzZWEiLCJwIjoiaiJ9)
Write possible network errors to the ahjoStatus.

## Additional notes :spiral_notepad:

[HL-1514]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HL-1515]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3526.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3526.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3526.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3526.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3526.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
