### PR TITLE
fix: modify batches to better support TALPA and handler's work (HL-1053)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

* Separate batches that are pending:
  * Those that wait for AHJO decisions `awaiting_ahjo_decision` (tab 2 - inspection phase)
  * Those that wait for Talpa robot visit `accepted` and confirmed by robot with `sent_to_talpa` (tab3 - completion phase)
* Allow batch status to be set to `completed` (this happens when "Archive" button is pressed in web UI)
* Refactor code by splitting components into new files
* Change `rejected` application's batch decision status from `rejected` to `completed`
* Fix animations when changing batch status

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2615.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2615.dev.hel.ninja** :rocket::rocket::rocket:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
