### PR TITLE
fix: order of lines; € per month; 55yr pay subsidy title if needed

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Small template fixes for PDF summary reported by @JanneJuhola 

FI:
[download (2).pdf](https://github.com/City-of-Helsinki/yjdh/files/13543760/download.2.pdf)

SV:
[download (1).pdf](https://github.com/City-of-Helsinki/yjdh/files/13543761/download.1.pdf)

EN:
[download.pdf](https://github.com/City-of-Helsinki/yjdh/files/13543762/download.pdf)

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2547.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2547.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2547.dev.hel.ninja :laughing::tada::tada::tada:

**Review by JanneJuhola — APPROVED** [review]

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2547.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2547.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
