### PR TITLE
fix: instalment issues (hl-1496 cont.)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

* implement tag wrapper for talpa status for 1st instalments that have gone through ahjo process
* fix issue where 1st instalment was zero or negative
  * ahjo process incomplete
  * above and with two instalments
* make JSX logic easier to read

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3576.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3576.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3576.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr3576.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
