### PR TITLE
YJDH-689 | feat(shared): add type for autoComplete property in React

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(shared): add type for autoComplete property in React

related to:
https://github.com/City-of-Helsinki/yjdh/pull/2767#pullrequestreview-1845768040

Caveats:
 - Not exact (i.e. allows combinations not allowed by HTML
   specification)
   - e.g. "name address-line1" is allowed here but should not be
   - "inappropriate for a control" clause in HTML specification is not
	 handled, which means that this type allows all combinations for all
	 control groups, i.e. for Date, Month, Multiline, Numeric, Password,
	 Tel, Text, URL and Username.
 - Not complete (i.e. does not allow all combinations allowed by HTML
   specification)
   - e.g. "section-arbitrary-named-group-name-123" is not allowed here
   but should be

autocomplete in HTML specification:
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

refs YJDH-689 (PR #2767 comment mentioned possible autoComplete type)

## Issues :bug:

[YJDH-689](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-689)

## Additional notes :spiral_notepad:

[YJDH-689]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2782.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://tet-pr2782.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Review by nikomakela — COMMENTED** [review]
I'm just afraid whether this is too intense typing. For example the React library (the @types-library for it) types the autocomplete as just `string | undefined` like was done here earlier. I was kind of hoping that this type would be maintained by some well known and much used external library.

Do we really get that much benefit of this, that we should apply a batch of couple of hundreds of lines of code that we shoulkd then self maintain? Aren't we using just `"on" | "off" | "" | undefined`?

Nice typing anyway! 😄

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-employer-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-employer-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**ADMIN branch is deployed to platta: https://tet-admin-ui-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tet-admin-ui-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://kesaseteli-handler-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-handler-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://tet-youth-ui-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tet-youth-ui-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://kesaseteli-youth-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-youth-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
How do you see this shared code change Helsinki benefit team @sirtawast, @rikuke & @EmiliaMakelaVincit? I'm a bit biased as I made the code and I admit I am perhaps trying to hold on to the code a bit as having created it.

Pros:
 - Type safe
 - Allows `autocomplete` string autocompletion / selection from dropdown in supporting IDEs
 - There are tests
 - Quite comprehensive

Cons:
 - Maintenance cost in case HTML spec changes
 - Type safe aspects may sometimes be a hurdle to use
 - Not comprehensive related to "section-<arbitrary name>" first optional token
 - Not as restrictive as HTML spec related to different input types (e.g. TextInput vs. Date)
 
`autocomplete` attribute was not used before last week in this YJDH monorepo AFAIK so adding it and typing it makes the situation better than before IMO.

I'm not saying we must include this, but as counterargument to excluding this how often does the HTML spec's `autocomplete` part change and if it does, will the code in this repo be using those values as they were not used before at all? The basic values like `on`, `off`, `street-address` etc are supported already and of course new values may come but adding them to the type should be quite trivial unless something drastically changes in the spec.

**Comment by sirtawast** [comment]
@karisal-anders it's a good addition. I'm not familiar with this spec at all but it serves our purpose as we have tickets such as these https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/HL/boards/204/backlog?selectedIssue=HL-71&text=esit%C3%A4yt.

**Comment by EmiliaMakelaVincit** [comment]
Yeah, this seems fine to me too.

**Comment by karisal-anders** [comment]
[Force pushed](https://github.com/City-of-Helsinki/yjdh/compare/8f2863692abc0ea182f14bf720a5dc6f0a15fbe9..7f4d73f0371cd0047928f96d70108a089aa79d1d) the removal of `log in` (no spaces in the tokens) token, nothing else changed.

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://tet-pr2782.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2782.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2782.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ADMIN branch is deployed to platta: https://tet-admin-ui-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-employer-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tet-admin-ui-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-employer-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://kesaseteli-handler-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-handler-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://tet-youth-ui-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tet-youth-ui-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://kesaseteli-youth-pr2782.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
@nikomakela Helsinki benefit team mostly seems ok with including this, how do you see this with this added information?

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-youth-pr2782.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]
I heard that this was talked with every monorepo team, so I will approve this because it was ok for everybody.

**Comment by karisal-anders** [comment]
> I heard that this was talked with every monorepo team, so I will approve this because it was ok for everybody.

Not all, I asked for comments from Helsinki benefit team and two of their members were mostly ok (my impression) with including this.

**Pull request merged**
