### PR TITLE
fix: round alteration recovery amount down

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1490](https://helsinkisolutionoffice.atlassian.net/browse/HL-1490?atlOrigin=eyJpIjoiYmMxNzY5OWU0ZGEyNGJkMGEyMTJhZGE2OWQwZmJkZDEiLCJwIjoiaiJ9)

Round alteration.recovery_amount down when it is saved or updated.

[HL-1502](https://helsinkisolutionoffice.atlassian.net/browse/HL-1502)
Show both instalments in the csv reports, even if they are not due yet.

## Additional notes :spiral_notepad:

[HL-1490]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HL-1502]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3648.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3648.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3648.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3648.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3648.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3648.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3648.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3648.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
