### PR TITLE
feat: Hl 1502 csv changes

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1502](https://helsinkisolutionoffice.atlassian.net/browse/HL-1502)
- Use instalment.amount_paid in talpa csv.
- Add instalment 1 and instalment 2 to powerBI csv report and handler csv report.
## Additional notes :spiral_notepad:

[HL-1502]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3618.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3618.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3618.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3618.dev.hel.ninja :laughing::tada::tada::tada:

**Review by JanneJuhola — APPROVED** [review]

**Pull request merged**
