### PR TITLE
fix: calculation and pay subsidies would not reset if changed on edit (hl-1110, hl-1127, hl-1130) 

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Fix an issue with calculation and pay subsidies showing wrong if any of these change:

* Pay subsidy type
* Apprenticeship yes/no

Also sets new expense information (salary, vacation expenses, other expenses) as calculation defaults.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2847.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2847.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2847.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2847.dev.hel.ninja :laughing::tada::tada::tada:

**Review by EmiliaMakelaVincit — APPROVED** [review]

**Pull request merged**
