### PR TITLE
Hl 1445 add fields

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Adds the columns needed for the PowerBI report.
## Additional notes :spiral_notepad:
[power_bi_data_20240919_082825.csv](https://github.com/user-attachments/files/17055992/power_bi_data_20240919_082825.csv)

### CODE REVIEW

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3334.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3334.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3334.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3334.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
