### PR TITLE
HL-506, YJDH-514, TETP-158: change CSRF_COOKIE_NAME to yjdhcsrftoken

### PR DESCRIPTION
**Pull request by haavikko**
## Description :sparkles:

Change CSRF_COOKIE_NAME to yjdhcsrftoken in all YJDH projects

### CODE REVIEW

**Review by melniiv — APPROVED** [review]
LGTM

**Review by karisal-anders — APPROVED** [review]
LGTM but needs to be tested, ok to merge as is from my side.

**Review by nenonja — APPROVED** [review]
> The conf value must be set to platta I guess?

Yep, or removed altogether as the default is already correct.

**Review by mattikl — APPROVED** [review]
Reviewed and tested that TET Admin app works as excepted (calls to backend API work, yjdhcsrftoken cookie gets set).

**Pull request merged**
