### PR TITLE
fix: various cloning issues (hl-1539)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

* in frontend, change translation for clone button and hide them in decision proposal steps
* add missing ahjo status "submitted_but_not_sent_to_ahjo"
* ensure duplicated application is of type "applicant" if applicant is creating the clone
* clone only specific attachments
* copy some test values on handler clone if address information is missing

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3577.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3577.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3577.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3577.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
