### PR TITLE
fix: tests for new handler application (HL-812)

### PR DESCRIPTION
**Pull request by mjturt**
## Description :sparkles:

Tests for new handler application. Also, skip the broken tests, so the tests can be activated on pipeline.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2307.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2307.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2307.dev.hel.ninja** :rocket::rocket::rocket:

**Review by sirtawast — APPROVED** [review]
We'll need to revisit these soon, but skipping is ok for now.

**Pull request merged**
