### PR TITLE
chore: add a migration command to create needed proposal drafts

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Tool to create missing proposal drafts for older applications.

## Test

0. have some old applications or create with `python manage.py seed --number=10`
1. `git checkout main && git pull`
2. migrate by restarting backend docker container
3. run `python manage.py create-proposal-drafts`
4. you can re-run command by removing created rows from `bf_applications_decision_proposal_draft` table

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2931.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2931.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2931.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2931.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
