### PR TITLE
feat: add AD username column to user

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Add ad_username column to User so that when applications are sent to Ahjo REST api, the application handler's ad username can be sent as well.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2499.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2499.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2499.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2499.dev.hel.ninja** :rocket::rocket::rocket:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
