### PR TITLE
fix: resolve pip problems

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

* Move openpyxl from dedv dependency to a requirement
* Patch pip-tools to a working version
* Do not use `-c` flag in requirements-dev.txt as it was never inteded to be used in this use case.

### CODE REVIEW

**Review by EmiliaMakelaVincit — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3125.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3125.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3125.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3125.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3125.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
