### PR TITLE
fix: secret decision xml formatting

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1256 ](https://helsinkisolutionoffice.atlassian.net/browse/HL-1256?atlOrigin=eyJpIjoiZTlhZDViNDQyYTY1NDg0Zjk5ZTU1NDdhOThiNzhiNzciLCJwIjoiaiJ9) Fix formatting issues (see screenshot) in the secret decision XM
## Screenshots :camera_flash:
MicrosoftTeams-image

### CODE REVIEW

**Review by JanneJuhola — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2902.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2902.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2902.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2902.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2902.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
