### PR TITLE
fix: no calculation data for rejected applications

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1353](https://helsinkisolutionoffice.atlassian.net/browse/HL-1353?atlOrigin=eyJpIjoiNzAzZDAxYmNlODM0NGU3OGI4MmQ4MGUwMWQ2YTQwYzAiLCJwIjoiaiJ9)
Fix for error that occurs when AhjoXMLBuilder tries to generate a secret xml attachment for a rejected application that has no calculation.
## Additional notes :spiral_notepad:

[HL-1353]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3080.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3080.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3080.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3080.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3080.dev.hel.ninja :laughing::tada::tada::tada:

**Review by EmiliaMakelaVincit — APPROVED** [review]

**Pull request merged**
