### PR TITLE
Fix language menu button aria label for better accessibility

### PR DESCRIPTION
**Pull request by ngocdh236**

### CODE REVIEW

**Review by nenonja — CHANGES_REQUESTED** [review]
Translation is broken:
Screenshot 2022-03-28 at 11 32 29 AM
Screenshot 2022-03-28 at 11 32 57 AM

**Comment by ngocdh236** [comment]
> Translation is broken: Screenshot 2022-03-28 at 11 32 29 AM Screenshot 2022-03-28 at 11 32 57 AM



> Translation is broken: Screenshot 2022-03-28 at 11 32 29 AM Screenshot 2022-03-28 at 11 32 57 AM

@nenonja hi, is this still happening after you re-run the application? if yes which application is this so I can check the translations files?

**Comment by nenonja** [comment]
> > Translation is broken: Screenshot 2022-03-28 at 11 32 29 AM Screenshot 2022-03-28 at 11 32 57 AM
> 
> @nenonja hi, is this still happening after you re-run the application? if yes which application is this so I can check the translations files?

Just check the html code here: https://ks-youth-961.test.kuva.hel.ninja/ (refresh if the site shows error)

**Comment by ngocdh236** [comment]
> > > Translation is broken: Screenshot 2022-03-28 at 11 32 29 AM Screenshot 2022-03-28 at 11 32 57 AM
> > 
> > 
> > @nenonja hi, is this still happening after you re-run the application? if yes which application is this so I can check the translations files?
> 
> Just check the html code here: https://ks-youth-961.test.kuva.hel.ninja/ (refresh if the site shows error)

I realize that the deployment was done before I fixed the translations for ks apps, how can I deploy again..?

**Pull request merged**
