### PR TITLE
fix: convert spaces to dashes in ahjo case page link (HL-1240)

### PR DESCRIPTION
**Pull request by EmiliaMakelaVincit**

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2897.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2897.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2897.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2897.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr2897.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by JanneJuhola — APPROVED** [review]

**Review by sirtawast — CHANGES_REQUESTED** [review]
Accessibility problem with window.open?

Would this pattern be possible?
https://hds.hel.fi/storybook/react/?path=/docs/components-button--link-button

**Review by sirtawast — APPROVED** [review]
All good after `role="link"` addition to `<Button>`

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2897.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2897.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2897.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2897.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2897.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
