### PR TITLE
HL-343 | Browser tests

### PR DESCRIPTION
**Pull request by Nizar-Rahme**

### CODE REVIEW

**Comment by Nizar-Rahme** [comment]
The tests run nicely in the local env, but the review env still throwing CORS errors even though I added CORS_ALLOW_ALL_ORIGINS: 1 to the Github workflow, maybe @quyenlq can give it a look when he’s back.
This is the review environment URL: https://helsinkibenefit-bf-appl-580.test.kuva.hel.ninja

**Comment by karisal-anders** [comment]
To let you know rebasing on `develop` will make the browser tests in **(KS EMPLOYER) Build & Review & Acceptance tests / KS Acceptance tests (ks-youth) (pull_request)** pass as they were fixed with the merging of PR #583.

**Comment by nenonja** [comment]
> The tests run nicely in the local env, but the review env still throwing CORS errors even though I added CORS_ALLOW_ALL_ORIGINS: 1 to the Github workflow, maybe @quyenlq can give it a look when he’s back. This is the review environment URL: https://helsinkibenefit-bf-appl-580.test.kuva.hel.ninja

I tried to add few missing cors settings but it still didnt work.

**Comment by nenonja** [comment]
It seemed that the valult values has vanished, the same problem as kesaseteli had: https://vault-tdchygv7dq-lz.a.run.app/ui/vault/secrets/review/show/yjdh-bf-bknd-review
I reverted the values and let's see if it works after rebuild

**Comment by nenonja** [comment]
> It seemed that the valult values has vanished, the same problem as kesaseteli had: https://vault-tdchygv7dq-lz.a.run.app/ui/vault/secrets/review/show/yjdh-bf-bknd-review I reverted the values and let's see if it works after rebuild

didnt fix the cors problem

**Comment by quyenlq** [comment]
> > It seemed that the valult values has vanished, the same problem as kesaseteli had: https://vault-tdchygv7dq-lz.a.run.app/ui/vault/secrets/review/show/yjdh-bf-bknd-review I reverted the values and let's see if it works after rebuild
> 
> didnt fix the cors problem

CORS problem is fixed now, but the browser test still fails

**Comment by Nizar-Rahme** [comment]
> CORS problem is fixed now, but the browser test still fails

Hi 🙋 
Now the tests are failing after submitting the first step due to the following error: 

image

**Comment by haavikko** [comment]
@melniiv the tests pass now, if this looks good to you now, I'll squash the commits and merge?

**Review by melniiv — APPROVED** [review]

**Comment by nenonja** [comment]
All browser tests pass now. HL browser test only fills 2 / 6 steps of the application, it needs to be finished later. There is one python lint failure that needs to be checked when backend guys are back.

**Pull request merged**
