### PR TITLE
HL-683 | Sentry source maps

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
The two NextJS frontends are integrated into Sentry using the `@sentry/nextjs `library. 
In order to tag a release and send the source maps into Sentry the` next.config.js` file needs to call the `WithSentryConfig()` function and the `sentry.client.config.js` and` sentry.server.config.js` files need exist in the same folder as the projects own `next.config.js` file when `next build `command is run.

Additionally the following variables need to be set in the Azure devops so that they are available when the build job is run.

SENTRY_ORG, SENTRY_PROJECT, SENTRY_URL, SENTRY_AUTH_TOKEN and SENTRY_RELEASE
Full description here [https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8235515911/Sentry+integration+notes](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8235515911/Sentry+integration+notes)

## Testing :alembic:
Deploy the branch and observe how the release is tagged with source maps into Sentry

## Screenshots :camera_flash:
Screenshot 2023-03-20 at 12 16 49

### CODE REVIEW

**Review by sirtawast — CHANGES_REQUESTED** [review]
I think it's better to hold this until [Next12 upgrade](https://github.com/City-of-Helsinki/yjdh/pull/1945). Stuff's heavily overlapping with `next.config.js`. Let's work together to get this implemented with Node v16 / Next v12 versions.

**Review by sirtawast — APPROVED** [review]

**Comment by karisal-anders** [comment]
- Checked out the branch locally
- Ran `docker compose -f .\docker-compose.handler.yml down --remove-orphans`
- Ran `docker compose -f .\docker-compose.handler.yml up --build`
- Tried opening https://localhost:3100/ or https://localhost:3200/ and got Internal Server Error

```
kesaseteli-handler   | Error: Cannot find 'sentry.client.config.ts' or 'sentry.client.config.js' in '/app/kesaseteli/handler'.
kesaseteli-handler   |     at getUserConfigFile (/app/node_modules/@sentry/nextjs/cjs/config/webpack.js:300:9)
kesaseteli-handler   |     at addSentryToEntryProperty (/app/node_modules/@sentry/nextjs/cjs/config/webpack.js:268:79)
```
and same for kesaseteli-youth i.e.
```
kesaseteli-youth     | Error: Cannot find 'sentry.client.config.ts' or 'sentry.client.config.js' in '/app/kesaseteli/youth'.
kesaseteli-youth     |     at getUserConfigFile (/app/node_modules/@sentry/nextjs/cjs/config/webpack.js:300:9)
kesaseteli-youth     |     at addSentryToEntryProperty (/app/node_modules/@sentry/nextjs/cjs/config/webpack.js:268:79)
```

**Comment by rikuke** [comment]
@karisal-anders I reworked the copying of the sentry config files. Doing it this way  adds 7 identical sentry.client.config.js-files and 7 sentry.server.config.js files into the repo..  But I don't see any other way, as Sentry requires these files to exist in the same folder as next.config.js for it to be able to tag a release and upload the sourcemaps.

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr1918.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr1918.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr1918.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr1918.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://handler-pr1918.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-pr1918.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://youth-pr1918.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by sirtawast** [comment]
> @karisal-anders I reworked the copying of the sentry config files. Doing it this way adds 7 identical sentry.client.config.js-files and 7 sentry.server.config.js files into the repo.. But I don't see any other way, as Sentry requires these files to exist in the same folder as next.config.js for it to be able to tag a release and upload the sourcemaps.

This is a basic pattern repeating throughout the monorepo: `tsconfig.json`, `testcaferc.js`, `next.config.js` to name a few.

**Review by karisal-anders — APPROVED** [review]
Approved. I'm not sure whether the test pipelines on Platta for Kesäseteli really disable sentry i.e. set NEXTJS_DISABLE_SENTRY to true anywhere. The review pipelines on Platta for Kesäseteli do that if I read the code correctly under https://dev.azure.com/City-of-Helsinki/yjdh-kesaseteli/_git/yjdh-kesaseteli-pipelines @terovirtanen Do you know if the test pipelines for Kesäseteli on Platta set NEXTJS_DISABLE_SENTRY to true somewhere?

**Pull request merged**
