### PR TITLE
fix: add missing migration file

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Add missing terms migration file. This one sets default  to empty string.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2545.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Review by mjturt — APPROVED** [review]

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2545.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2545.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2545.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2545.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
