### PR TITLE
chore: revisit logic on how and when to show alteration summary (hl-1472)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Alteration summary didn't show up if ahjo automation was not used. Change this and bunch of other logic on when to display this information

* Always display alterations in all envs: remove flag `NEXT_PUBLIC_ENABLE_ALTERATION_FEATURES`
* To display alteration, the application must have either
  * `handledByAhjoAutomation`, `ahjoCaseId` as _"HEL 20xx-xxxx"_ and `ahjoStatus` as _"details_received"_
  * `handledByAhjoAutomation` as _false_ and `batchStatus` as _"sent_to_talpa"_ (Talpa robot visit) or _"completed"_ (archived by handler after Talpa robot).

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3335.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3335.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3335.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3335.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
