### PR TITLE
HL-747, HL-799, HL-801, HL-802, HL-803, HL-809 | Improve UI for Ahjo / Talpa

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

New features:
* Improve handler's workflow
* Add "locked" state before sending batch to Ahjo
* Add fancy batch transitions when changing status
* Remove batch (also remove batch if it's freed of applications)
* Add confirmation when changing batch status or removing it with HDS dialog modal
* Remove two deprecated sections from https://localhost:3100/reports/

Resolves:
* HL-747
* HL-801
* HL-802
* HL-799
* HL-803
* HL-809

### CODE REVIEW

**Comment by sirtawast** [comment]
Figured it requires new tests and more python love.

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2074.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2074.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2074.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2074.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2074.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by sirtawast** [comment]
Python codecoverage now fixed!

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2074.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Review by rikuke — CHANGES_REQUESTED** [review]
Looks fine to me, fix the parts that are reported by GitHub Actions / Test and its good to go.

**Review by rikuke — APPROVED** [review]

**Pull request merged**
