### PR TITLE
Upgrade django-environ so that database url can be read correctly in PLATTA environment

### PR DESCRIPTION
**Pull request by haavikko**
## Description :sparkles:
same change was done in Kesäseteli

### CODE REVIEW

**Comment by klemmari1** [comment]
Just to clarify, upgrading `django-environ` did not solve anything in the end, it was just testing if it would solve the problem. In the end, the problem was to add some env variables `PSQL_HOST` `PSQL_PORT` that were removed for some reason. Those are used by pgbouncer.

**Review by klemmari1 — APPROVED** [review]
I'll approve this but probably won't solve the problem if you have DB connection issues.

**Comment by haavikko** [comment]
Yes, I was thinking the timeouts yesterday were due to this, but that was a transient error

**Comment by haavikko** [comment]
Anyway it's good to have the same versions in helsinki-benefit and kesäseteli

**Pull request merged**
