### PR TITLE
(DRAFT) YJDH-696 | Upgrade black/isort/flake8 to latest versions in all backends

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat: upgrade black/isort/flake8 to latest versions in all backends

also:
 - all backends
   - fix flake8 E721 ("Do not compare types, use 'isinstance()'")
	 warnings
	 - change `==` to `is` in type comparisons
	 - change `!=` to `is not` in type comparisons
   - make the dependency of .pre-commit-config.yaml's black/isort/flake8
	 versions and each backend's requirements explicit
 - benefit backend:
   - ignore flake8 F811 ("Redefinition of unused name from line n")
	 warning in ReceivedApplicationFactory's calculation post generation
	 function, so the pull request won't stall simply because of this
	 warning as the code has been like this already for some time.

refs YJDH-696

## Issues :bug:

[YJDH-696](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696)

## Additional notes :spiral_notepad:

[YJDH-696]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://tet-pr3162.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr3162.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://tet-pr3162.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-employer-pr3162.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3162.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3162.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3162.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-employer-pr3162.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3162.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**ADMIN branch is deployed to platta: https://tet-admin-ui-pr3162.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3162.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tet-admin-ui-pr3162.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
Closed as out of date. I'd replace black/isort/flake8 with ruff, having done so in other projects already.

**Pull request closed without merging**
