### PR TITLE
YJDH-687 | feat: upgrade django to 3.2.23 (i.e. latest 3.2.x) in all backends

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat: upgrade django to 3.2.23 (i.e. latest 3.2.x) in all backends

refs YJDH-687

## Issues :bug:

[YJDH-687](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-687)

## Additional notes :spiral_notepad:

[YJDH-687]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by karisal-anders** [comment]
Please could one of Helsinki benefit team code review your part (i.e. @rikuke, @sirtawast or @mjturt)?
Please could one of TET team code review your part (i.e. @arpargo or @tuomas777)?
Thank you!

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://tet-pr2520.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2520.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2520.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tet-admin-ui-pr2520.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2520.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2520.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://tet-youth-ui-pr2520.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2520.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2520.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
@arpargo & @tuomas777 About the TET's failing test in CI:

The failing test is a frontend test and should *probably* not be affected by a minor version upgrade of django.
Tried out with the current `main` branch & this PR's branch both:
```bash
docker compose -f compose.tet.yml up --build
docker exec -it te-admin bash
yarn te-admin:test
```
and both passed the [test which is failing in CI for TET](https://dev.azure.com/City-of-Helsinki/yjdh-tet/_build/results?buildId=138925&view=logs&j=417bb558-ddd8-5ea3-ece4-79e983960ca7&t=eb9aaf15-103b-5767-1b6f-ad8aa39692fc) when run locally in docker:
```
 PASS  src/components/editor/__tests__/Editor.test.tsx
  frontend/tet/admin/src/components/editor/Editor
    ✓ should show field values in form components (1031 ms)
    when submiting form
      ○ skipped shows errors if empty values on required fields
      ○ skipped shows error notification if form is not valid
```

Here's the error in CI for TET for the same [test](https://dev.azure.com/City-of-Helsinki/yjdh-tet/_build/results?buildId=138925&view=logs&j=417bb558-ddd8-5ea3-ece4-79e983960ca7&t=eb9aaf15-103b-5767-1b6f-ad8aa39692fc):
```
FAIL src/components/editor/__tests__/Editor.test.tsx
  frontend/tet/admin/src/components/editor/Editor
    ✕ should show field values in form components (1398 ms)
    when submiting form
      ○ skipped shows errors if empty values on required fields
      ○ skipped shows error notification if form is not valid

  ● frontend/tet/admin/src/components/editor/Editor › should show field values in form components

    TypeError: router[operation] is not a function

      18 |       // use shallow route when we are already on the same path (ignoring query params)
      19 |       const shallow = pagePath === router.pathname;
    > 20 |       void router[operation](path, undefined, { shallow });
         |                             ^
      21 |     },
      22 |     [locale, router, isAlreadyRouting]
      23 |   );

      at goToPage (../../shared/src/hooks/useGoToPage.ts:20:29)
      at onServerError (src/hooks/backend/useUserQuery.ts:14:28)
      at handleError (../../shared/src/error-handler/error-handler.ts:36:7)
      at ../../shared/src/hooks/useErrorHandler.ts:20:16
      at ../../node_modules/react-query/lib/core/notifyManager.js:67:18
      at NotifyManager.notifyFn (../../node_modules/react-query/lib/core/notifyManager.js:15:7)
      at ../../node_modules/react-query/lib/core/notifyManager.js:82:20
          at Array.forEach (<anonymous>)
      at ../../node_modules/react-query/lib/core/notifyManager.js:81:17
      at NotifyManager.batchedUpdates$1 [as batchNotifyFn] (../../node_modules/react-dom/cjs/react-dom.development.js:25979:12)
      at ../../node_modules/react-query/lib/core/notifyManager.js:80:16
```

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-employer-pr2520.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-employer-pr2520.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://kesaseteli-handler-pr2520.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-handler-pr2520.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://kesaseteli-youth-pr2520.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-youth-pr2520.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
