### PR TITLE
DRAFT: feat(ks-backend): testing review environment & EMAIL_HOST env variable

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(ks-backend): testing review environment & EMAIL_HOST env variable

DO NOT MERGE! THIS COMMIT IS FOR REVIEW ENVIRONMENT TESTING ONLY!

refs YJDH-682

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2401.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://kesaseteli-handler-pr2401.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-handler-pr2401.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://kesaseteli-youth-pr2401.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-employer-pr2401.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-employer-pr2401.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-youth-pr2401.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
Not needed anymore, testing was successful.

**Pull request closed without merging**
