### PR TITLE
feat: Hl 1575 instalment to accepted

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1575](https://helsinkisolutionoffice.atlassian.net/browse/HL-1575)
Enable the returning of an instalment from error_in_talpa status to accepted or paid status via  handlerUI.
## Screenshots :camera_flash:
Screenshot 2024-12-10 at 12 03 58
Screenshot 2024-12-10 at 12 04 07
Screenshot 2024-12-10 at 12 04 36

## Additional notes :spiral_notepad:

[HL-1575]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by JanneJuhola — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3642.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3642.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3642.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3642.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3642.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
