### PR TITLE
feature: updating backend api to use platta version of linkedevents

### PR DESCRIPTION
**Pull request by arpargo**
## Description :sparkles:
LinkedEvents old urls are going to stop working sooner or later so updating them to use the new environments that have been setup.

### CODE REVIEW

**Review by sirtawast — COMMENTED** [review]
My two cents: could use a constant. `linkedevents-api-dev.agw.arodevtest.hel.fi` is defined 39 (py) + 4 (ts) times.

**Comment by arpargo** [comment]
> My two cents: could use a constant. `linkedevents-api-dev.agw.arodevtest.hel.fi` is defined 39 (py) + 4 (ts) times.

This is true, but most of the mentions are inside test json payloads used for tests and I'd rather not try to poke around those to parametrize them.

Anyways, found some i could fix and found few missed urls.

**Review by tuomas777 — APPROVED** [review]
LGTM 👍

**Comment by tuomas777** [comment]
Actually the URL needs to be changed one more time, so let's not merge this yet 😅

**Comment by arpargo** [comment]
> Actually the URL needs to be changed one more time, so let's not merge this yet 😅

Didn't we actually just change the new platta urls to match the old urls so this PR is unnecessary?

**Comment by tuomas777** [comment]
Superseded by https://github.com/City-of-Helsinki/yjdh/pull/2339

**Pull request closed without merging**
