### PR TITLE
fix: redo various issues with typos and text flow (#2622)

### PR DESCRIPTION
**Pull request by sirtawast**
Fix broken builds caused by failing pytest.

This reverts and adds to commit c870fcb932b2eff85e3c03339a9fd859877ba274 which is a revert of a previous PR ♻️ .

## Description :sparkles:

Fix issue in test. Test would assert **littyen** but it should've been **liittyen** ofc 🤷 .

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2637.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2637.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2637.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mjturt — APPROVED** [review]

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2637.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2637.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
