### PR TITLE
HL-883 | Fix some issues with opening and locking application on handler's side

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

* Fix seeded applications not being able to be opened / locked by adding more required attachments
* Fix all  handler-generated applications throwing a validation violation by skipping user terms validation altogether
* Add toast error reporting if something goes wrong

### Note

On handler's side, there's still problems locking or opening an application when terms have been changed and old (although accepted) ones  are not in effect anymore. The locking and opening action uses general `PUT` on `/applications/{app_id}/` so it's an error prone process because of rigorous model validation. [There's a new ticket for this](https://helsinkisolutionoffice.atlassian.net/browse/HL-916).

There are two ways to implement a fix:

* Make custom endpoint
  * a new field to set application lock property on/off
  * or just change application status like now (possible status transition problems might arise)
* Loosen the requirements for term consent's approval
* Try using a different Serializer for `PATCH (partial_update)` actions and implement frontend to call endpoint with `PATCH instead of `PUT`

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2181.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2181.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2181.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2181.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mjturt — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2181.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Pull request merged**
