### PR TITLE
YJDH-345 | KS-Backend: Use Finnish PostgreSQL in Docker

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description :sparkles:

Based on discussion in https://github.com/docker-library/postgres/issues/725#issuecomment-624141851

### KS-Backend: Use Finnish PostgreSQL in Docker:

backend/docker/kesaseteli.Dockerfile:
 - Add finnish_postgres target based on postgres:12 which sets up the
   PostgreSQL image to use Finnish language and database collation

docker-compose.youth.yml:
 - Use the finnish_postgres target

Using finnish_postgres kesaseteli-db is initialized like this:
 - The database cluster will be initialized with locale "fi_FI.UTF-8".
 - The default database encoding has accordingly been set to "UTF8".
 - The default text search configuration will be set to "finnish".

Listing the databases in the kesaseteli-db using
```docker exec -it kesaseteli-db psql -Ukesaseteli -c"\l"```
now gives (Removed irrelevant information for compact output):

```
                       List of databases
    Name    |   Owner    | Encoding |   Collate   |    Ctype    |
------------+------------+----------+-------------+-------------+
 kesaseteli | kesaseteli | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 |
 postgres   | kesaseteli | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 |
 template0  | kesaseteli | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 |
 template1  | kesaseteli | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 |
```

### SchoolListView: Remove unnecessary custom sorter:

Now the underlying PostgreSQL database uses fi_FI.UTF-8 collation so the
sorting works without the custom sorter.

### ks-pytest.yml: Use Finnish PostgreSQL:

Use Finnish PostgreSQL in review environment's (KS) Python tests so
test_schools_list_returns_sorted_collection test from
applications/tests/test_schools_api.py passes in review environment.

## Issues :bug:

YJDH-345

## Testing :alembic:

If you need to you can drop the database volume so it gets recreated with the correct language and collation:
```
docker-compose -f .\docker-compose.youth.yml down
docker volume rm yjdh_pgdata
yarn youth --build
```

### CODE REVIEW

**Comment by karisal-anders** [comment]
Even though in the review environment the browser tests don't pass, see [test run](https://github.com/City-of-Helsinki/yjdh/runs/4689636657?check_suite_focus=true) and related bug [ticket](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-374) (This ticket is in Finnish and it may or may not be the same bug as the error messages are not identical),
locally they do:

`browser-test:ci` and `browser-test` pass locally:
```
frontend/kesaseteli/youth> yarn browser-test:ci
yarn run v1.22.17
$ testcafe 'chrome:headless --disable-gpu --window-size="1249,720" --ignore-certificate-errors-spki-list="8sg/cl7YabrOFqSqH+Bu0e+P27Av33gWgi8Lq28DW1I=,gJt+wt/T3afCRkxtMMSjXcl/99sgzWc2kk1c1PC9tG0=,zrQI2/1q8i2SRPmMZ1sMntIkG+lMW0legPFokDo3nrY="' --screenshots path=report,fullPage=true --video report --reporter spec,custom,html:report/index.html testcafe.dotenv.js browser-tests/
|
 Running tests in:
 - Chrome 96.0.4664.110 / Windows 10

 Frontpage
 √ can fill up youth application

 Frontpage
 √ can change to languages


 2 passed (25s)
Done in 45.94s.
frontend/kesaseteli/youth> yarn browser-test
yarn run v1.22.17
$ testcafe 'chrome --ignore-certificate-errors --ignore-urlfetcher-cert-requests --window-size="1249,720"' testcafe.dotenv.js browser-tests/
 Running tests in:
 - Chrome 96.0.4664.110 / Windows 10

 Frontpage
 √ can fill up youth application

 Frontpage
 √ can change to languages


 2 passed (20s)
Done in 39.08s.
```

**Comment by karisal-anders** [comment]
<ins>The tests pass now</ins>, they were fixed with the merging of PR #583 and rebasing on `develop` after that.

**Review by haavikko — APPROVED** [review]
Looks good, the ordering is now defined in the correct (database) layer

**Comment by karisal-anders** [comment]
I'm merging this to `develop` even though .github/dependabot.yml check is failing.
I have made a ticket [YJDH-403](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-403) about this issue and PR #592 for fixing it.
To the best of my knowledge this check failing is not caused by the changes in this pull request.

**Pull request merged**
