### PR TITLE
fix: prefetch alterations regardless of auth mock flag

### PR DESCRIPTION
**Pull request by EmiliaMakelaVincit**
## Description :sparkles:
Since the prefetch was missing in a real usage scenario, the applicant UI failed to find any alterations and also didn't return even an empty array, breaking views that expected one to be present.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3043.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3043.dev.hel.ninja** :rocket::rocket::rocket:

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3043.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3043.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
