### PR TITLE
feat: visualise instalments and alterations (hl-1496)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Backend

* Use alteration sum functions to get reduced amounts of benefits
* Add amount_paid to store the amount reduced by alterations when talpa robot visits

Frontend

* Visualise calculations with alterations in a single place
* Reduce the amount from 2nd instalment if possible
  * If not, show how much recoveries have to be paid 
 
2nd instalment

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3547.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3547.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3547.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3547.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
