### PR TITLE
feat: add accordion to decision box to list instalments (hl-1497)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Continued from #3498. 

* Implement "Instalments" accordion into decision box
  * Lists both instalments: the default one and the second too.
* Add `status` validation to `InstalmentSerializer`
* Make instalment patch endpoint change application to `archived` if second instalment is cancelled
* Cancelling 2nd instalment from `ApplicationListForInstalments` now uses popup
* Other minor details changed for `ApplicationListForInstalments`

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3515.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3515.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3515.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3515.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
