### PR TITLE
feat: 2nd instalment due date into csv

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1576](https://helsinkisolutionoffice.atlassian.net/browse/HL-1576)
Add new columns to handler csv reports and PowerBI report:
- the decided amount for instalment 1 and 2
- the actual payable amount for instalment 2
- the due date of instalment 2

Should fix [HL-1571](https://helsinkisolutionoffice.atlassian.net/browse/HL-1571?atlOrigin=eyJpIjoiNmJiMmU4MDUwNzJiNDU5NWIyNTZhN2U5NTNhYjEwMGMiLCJwIjoiaiJ9) also.

Change pruned_applications_csv_service to talpa_applications_csv in tests, because the name was confusing.

Use the recovered_amount property of instalment in talpa CSV export  and the other csv reports.
## Additional notes :spiral_notepad:

[HL-1576]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HL-1571]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3635.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3635.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3635.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3635.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3635.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3635.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3635.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3635.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3635.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
