### PR TITLE
feat: store ahjo validation errors to ahjoStatus

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1454](https://helsinkisolutionoffice.atlassian.net/browse/HL-1454)

Store any validation errors to last ahjoStatus when receiving 400 Bad Request from ahjo.
## Screenshots :camera_flash:
Screenshot 2024-09-20 at 14 51 54

## Additional notes :spiral_notepad:

[HL-1454]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3342.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3342.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3342.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3342.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3342.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
