### PR TITLE
feat: HL 1365 improve logging, HL-1363 don't block ahjo requests

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1365](https://helsinkisolutionoffice.atlassian.net/browse/HL-1365?atlOrigin=eyJpIjoiYTZiZjAwYzQ4NDU5NDEzNDliNDU1YTAwNjUzZWE1ZTMiLCJwIjoiaiJ9)
Improve logging and errors by printing timestamp and application number.

[HL-1363](https://helsinkisolutionoffice.atlassian.net/browse/HL-1363?atlOrigin=eyJpIjoiYzAyMjJjOWJiYzk2NDlmOWFlNzE2NGE4ODYyMDU3YjQiLCJwIjoiaiJ9)
When one AhjoRequest failed, the rest of the requests were not sent, this PR handles the exceptions so that the execution continues after an error is encountered and logged,this should also fix [HL-1366](https://helsinkisolutionoffice.atlassian.net/browse/HL-1366?atlOrigin=eyJpIjoiNDI2YjBmMmZjMTA3NDI1NmI3NzI0MGJhZjNiYjUzOTUiLCJwIjoiaiJ9) where PUT requests were not executed if one failed.
## Additional notes :spiral_notepad:

[HL-1365]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1363]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1366]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3099.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3099.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3099.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3099.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
