### PR TITLE
fix: typo in Type

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
"ExterOnal" should be "External"

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2888.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2888.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2888.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2888.dev.hel.ninja** :rocket::rocket::rocket:

**Review by JanneJuhola — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2888.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
