### PR TITLE
YJDH-670 | feat(kesaseteli): update year 2024's target groups' ages in frontend

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(kesaseteli): update year 2024's target groups' ages in frontend

refs YJDH-670

## Issues :bug:

[YJDH-670](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-670)

## Additional notes :spiral_notepad:

[YJDH-670]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2768.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-employer-pr2768.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-handler-pr2768.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://kesaseteli-youth-pr2768.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-youth-pr2768.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
