### PR TITLE
Hl 1300 automation fix

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Fix quarter hourly jobs so that decision request is run only once instead of twice.
Adjust the query for decision request so that it will fetch applications  which have been `accepted` or` rejected`, their talpa status is `not_processed_by_talpa`, they have a `ahjo_case_id`, a `decisiontext` and their **latest** `ahjo_status` is `case_opened`.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2980.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2980.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2980.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2980.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2980.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
