### PR TITLE
YJDH-378 | KS-Backend: Unify activation link expiration

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description :sparkles:

1. Unify activation link expiration:

Replace YOUTH_APPLICATION_ACTIVATION_LINK_EXPIRATION_HOURS with
NEXT_PUBLIC_YOUTH_APPLICATION_ACTIVATION_LINK_EXPIRATION_SECONDS and
use 12 hours (i.e. 12 * 60 * 60 = 43200) as its default value.

2. Shorten activation link expiration variable name:

Rename NEXT_PUBLIC_YOUTH_APPLICATION_ACTIVATION_LINK_EXPIRATION_SECONDS
to NEXT_PUBLIC_ACTIVATION_LINK_EXPIRATION_SECONDS for ease of use.

## Issues :bug:

YJDH-378

## Additional notes :spiral_notepad:

### CODE REVIEW

**Comment by karisal-anders** [comment]
Even though in the review environment the browser tests don't pass, see [test run](https://github.com/City-of-Helsinki/yjdh/runs/4658254954?check_suite_focus=true) and related bug [ticket](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-374) (This ticket is in Finnish and it may or may not be the same bug as the error messages are not identical),
locally they do:

`browser-test` passes locally:
```
frontend/kesaseteli/youth> yarn browser-test
yarn run v1.22.17
$ testcafe 'chrome --ignore-certificate-errors --ignore-urlfetcher-cert-requests --window-size="1249,720"' testcafe.dotenv.js browser-tests/
 Running tests in:
 - Chrome 96.0.4664.110 / Windows 10

 Frontpage
 √ can fill up youth application

 Frontpage
 √ can change to languages


 2 passed (19s)
Done in 38.30s.
```

`browser-test:ci` passes locally:
```
frontend/kesaseteli/youth> yarn browser-test:ci
yarn run v1.22.17
$ testcafe 'chrome:headless --disable-gpu --window-size="1249,720" --ignore-certificate-errors-spki-list="8sg/cl7YabrOFqSqH+Bu0e+P27Av33gWgi8Lq28DW1I=,gJt+wt/T3afCRkxtMMSjXcl/99sgzWc2kk1c1PC9tG0=,zrQI2/1q8i2SRPmMZ1sMntIkG+lMW0legPFokDo3nrY="' --screenshots path=report,fullPage=true --video report --reporter spec,custom,html:report/index.html testcafe.dotenv.js browser-tests/
-
 Running tests in:
 - Chrome 96.0.4664.110 / Windows 10

 Frontpage
 √ can fill up youth application

 Frontpage
 √ can change to languages


 2 passed (20s)
Done in 39.58s.
```

**Comment by karisal-anders** [comment]
<ins>The tests pass now</ins>, they were fixed with the merging of PR #583 and rebasing on `develop` after that.

**Review by haavikko — APPROVED** [review]
Looks good to me! Using number of hours seemed clearer, but I'm assuming the unification required the use of seconds.

**Comment by karisal-anders** [comment]
> Looks good to me! Using number of hours seemed clearer, but I'm assuming the unification required the use of seconds.

I preferred the use of hours myself too but agreed to go with seconds to support frontend testing where setting a very small non-zero value for the expiration time is useful.

**Pull request merged**
