### PR TITLE
HL-765 | Upgrade to Node v18

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

It seems Node v16 is out of date this October already. Bump to Node v18.

## Issues so far

* ~[OpenSSL problem](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported) ([log](https://github.com/City-of-Helsinki/yjdh/pull/2015#issuecomment-1534244043))~
  * Resolved: add `--openssl-legacy-provider` to `yarn build` to mitigate. This should be resolved properly in NextJS v12 PR.
* ~Some TypeScript circular dependency errors detected in `yarn build` (TET)~
  * ~Resolved: continue using `@types/node@^17.0.43` typings until TET's circular mapping issue is resolved~
  * Resolved: use ts-ignore to get rid of 3rd party lib nags

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by sirtawast** [comment]
```#28 [staticbuilder 4/6] RUN yarn build
#28 0.460 yarn run v1.22.10
#28 0.495 $ next build
#28 1.538 info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
#28 1.832 notice- Sentry is disabled (NEXTJS_DISABLE_SENTRY)
#28 1.835 warn  - You have enabled experimental feature(s).
#28 1.835 warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
#28 1.836 
#28 1.853 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#28 1.854 This information is used to shape Next.js' roadmap and prioritize features.
#28 1.854 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#28 1.854 https://nextjs.org/telemetry
#28 1.854 
#28 1.875 Browserslist: caniuse-lite is outdated. Please run:
#28 1.875 npx browserslist@latest --update-db
#28 1.875 
#28 1.875 Why you should do it regularly:
#28 1.875 https://github.com/browserslist/browserslist#browsers-data-updating
#28 1.926 info  - Checking validity of types...
#28 16.57 warn  - No ESLint configuration detected. Run next lint to begin setup
#28 16.57 info  - Creating an optimized production build...
#28 16.61 info  - Using the createRoot API for React
#28 16.88 Browserslist: caniuse-lite is outdated. Please run:
#28 16.88 npx browserslist@latest --update-db
#28 16.88 
#28 16.88 Why you should do it regularly:
#28 16.88 https://github.com/browserslist/browserslist#browsers-data-updating
#28 17.08 node:internal/crypto/hash:71
#28 17.08   this[kHandle] = new _Hash(algorithm, xofLen);
#28 17.08                   ^
#28 17.08 
#28 17.08 Error: error:0308010C:digital envelope routines::unsupported
#28 17.08     at new Hash (node:internal/crypto/hash:71:19)
#28 17.08     at Object.createHash (node:crypto:133:10)
#28 17.08     at BulkUpdateDecorator.hashFactory (/app/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
#28 17.08     at BulkUpdateDecorator.update (/app/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
#28 17.08     at /app/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
#28 17.08     at processTicksAndRejections (node:internal/process/task_queues:82:21)
#28 17.08     at runNextTicks (node:internal/process/task_queues:64:3)
#28 17.08     at process.processImmediate (node:internal/timers:447:9) {
#28 17.08   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#28 17.08   library: 'digital envelope routines',
#28 17.08   reason: 'unsupported',
#28 17.08   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#28 17.08 }
#28 17.08 
#28 17.08 Node.js v18.16.0
#28 17.13 error Command failed with exit code 1.
#28 17.13 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#28 ERROR: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

#10 [production  7/12] RUN yarn install --production --check-files --ignore-scripts --prefer-offline && yarn cache clean --force
#10 CANCELED
------
 > [staticbuilder 4/6] RUN yarn build:
#28 17.08     at process.processImmediate (node:internal/timers:447:9) {
#28 17.08   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#28 17.08   library: 'digital envelope routines',
#28 17.08   reason: 'unsupported',
#28 17.08   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#28 17.08 }
#28 17.08 
#28 17.08 Node.js v18.16.0
#28 17.13 error Command failed with exit code 1.
#28 17.13 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:91
--------------------
  89 |     WORKDIR /app/$PROJECT/$FOLDER/
  90 |     
  91 | >>> RUN yarn build
  92 |     
  93 |     # Clean all dependencies (this should avoid caching + missing /pages directory problem)
--------------------
error: failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

Traceback (most recent call last):
  File "/app/devops", line 243, in <module>
    do.run_command()
  File "/app/devops", line 78, in run_command
    getattr(self, command)(**args)
  File "/app/devops", line 96, in create_images
    d.build_stages(push_images=True)
  File "/app/kolga/libs/docker.py", line 236, in build_stages
    image = self.build_stage(
  File "/app/kolga/libs/docker.py", line 289, in build_stage
    logger.std(result, raise_exception=True)
  File "/app/kolga/utils/logger.py", line [141](https://github.com/City-of-Helsinki/yjdh/actions/runs/4879761330/jobs/8706642929?pr=2015#step:4:142), in std
    raise Exception(output_string)
Exception: 
stdout:

stderr:
#2 [internal] load .dockerignore
#2 transferring context: 1.77kB 0.0s done
#2 DONE 0.0s

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 3.85kB 0.0s done
#1 DONE 0.0s

#3 [internal] load metadata for docker.io/helsinkitest/node:18-slim
#3 DONE 0.1s

#8 [production  1/12] FROM docker.io/helsinkitest/node:18-slim@sha256:eab242cd97166407e976e5bbe09e52aebe7bcc5c6a082c2005e56a158865a2dc
#8 resolve docker.io/helsinkitest/node:18-slim@sha256:eab242cd97166407e976e5bbe09e52aebe7bcc5c6a082c2005e56a158865a2dc done
#8 CACHED

#7 [production  2/12] WORKDIR /app
#7 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 76.12kB 0.1s done
#6 DONE 0.1s

#20 [appbase  3/10] RUN yarn config set ignore-engines true
#20 CACHED

#9 [appbase  2/10] RUN yarn policies set-version 1.22.10
#9 CACHED

#17 [appbase  6/10] COPY --chown=appuser:appuser kesaseteli/employer/package.json kesaseteli/employer/package.json
#17 CACHED

#15 [appbase  8/10] COPY --chown=appuser:appuser shared/package.json shared/package.json
#15 CACHED

#31 [staticbuilder 1/6] WORKDIR /app
#31 CACHED

#14 [appbase  9/10] RUN yarn --frozen-lockfile --check-files --network-timeout 600000 && yarn cache clean --force
#14 CACHED

#13 [appbase 10/10] COPY --chown=appuser:appuser . .
#13 CACHED

#18 [appbase  5/10] COPY --chown=appuser:appuser package.json yarn.lock ./
#18 CACHED

#19 [appbase  4/10] WORKDIR /app
#19 CACHED

#16 [appbase  7/10] COPY --chown=appuser:appuser kesaseteli/shared/package.json* kesaseteli/shared/package.json
#16 CACHED

#30 [staticbuilder 2/6] COPY --chown=appuser:appuser . .
#30 CACHED

#29 [staticbuilder 3/6] WORKDIR /app/kesaseteli/employer/
#29 DONE 0.0s

#5 [production  3/12] COPY --chown=appuser:appuser package.json yarn.lock lerna.json ./
#5 DONE 0.0s

#4 [production  4/12] COPY --chown=appuser:appuser kesaseteli/employer/package.json kesaseteli/employer/package.json
#4 DONE 0.0s

#12 [production  5/12] COPY --chown=appuser:appuser kesaseteli/shared/package.json kesaseteli/shared/package.json
#12 DONE 0.0s

#11 [production  6/12] COPY --chown=appuser:appuser shared/package.json shared/package.json
#11 DONE 0.0s

#10 [production  7/12] RUN yarn install --production --check-files --ignore-scripts --prefer-offline && yarn cache clean --force
#10 0.412 yarn install v1.22.19
#10 0.545 [1/5] Validating package.json...
#10 0.552 [2/5] Resolving packages...
#10 1.447 [3/5] Fetching packages...
#10 ...

#28 [staticbuilder 4/6] RUN yarn build
#28 0.460 yarn run v1.22.10
#28 0.495 $ next build
#28 1.538 info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
#28 1.832 notice- Sentry is disabled (NEXTJS_DISABLE_SENTRY)
#28 1.835 warn  - You have enabled experimental feature(s).
#28 1.835 warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
#28 1.836 
#28 1.853 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#28 1.854 This information is used to shape Next.js' roadmap and prioritize features.
#28 1.854 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#28 1.854 https://nextjs.org/telemetry
#28 1.854 
#28 1.875 Browserslist: caniuse-lite is outdated. Please run:
#28 1.875 npx browserslist@latest --update-db
#28 1.875 
#28 1.875 Why you should do it regularly:
#28 1.875 https://github.com/browserslist/browserslist#browsers-data-updating
#28 1.926 info  - Checking validity of types...
#28 16.57 warn  - No ESLint configuration detected. Run next lint to begin setup
#28 16.57 info  - Creating an optimized production build...
#28 16.61 info  - Using the createRoot API for React
#28 16.88 Browserslist: caniuse-lite is outdated. Please run:
#28 16.88 npx browserslist@latest --update-db
#28 16.88 
#28 16.88 Why you should do it regularly:
#28 16.88 https://github.com/browserslist/browserslist#browsers-data-updating
#28 17.08 node:internal/crypto/hash:71
#28 17.08   this[kHandle] = new _Hash(algorithm, xofLen);
#28 17.08                   ^
#28 17.08 
#28 17.08 Error: error:0308010C:digital envelope routines::unsupported
#28 17.08     at new Hash (node:internal/crypto/hash:71:19)
#28 17.08     at Object.createHash (node:crypto:133:10)
#28 17.08     at BulkUpdateDecorator.hashFactory (/app/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
#28 17.08     at BulkUpdateDecorator.update (/app/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
#28 17.08     at /app/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
#28 17.08     at processTicksAndRejections (node:internal/process/task_queues:82:21)
#28 17.08     at runNextTicks (node:internal/process/task_queues:64:3)
#28 17.08     at process.processImmediate (node:internal/timers:447:9) {
#28 17.08   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#28 17.08   library: 'digital envelope routines',
#28 17.08   reason: 'unsupported',
#28 17.08   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#28 17.08 }
#28 17.08 
#28 17.08 Node.js v18.16.0
#28 17.13 error Command failed with exit code 1.
#28 17.13 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#28 ERROR: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

#10 [production  7/12] RUN yarn install --production --check-files --ignore-scripts --prefer-offline && yarn cache clean --force
#10 CANCELED
------
 > [staticbuilder 4/6] RUN yarn build:
#28 17.08     at process.processImmediate (node:internal/timers:447:9) {
#28 17.08   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#28 17.08   library: 'digital envelope routines',
#28 17.08   reason: 'unsupported',
#28 17.08   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#28 17.08 }
#28 17.08 
#28 17.08 Node.js v18.16.0
#28 17.13 error Command failed with exit code 1.
#28 17.13 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:91
--------------------
  89 |     WORKDIR /app/$PROJECT/$FOLDER/
  90 |     
  91 | >>> RUN yarn build
  92 |     
  93 |     # Clean all dependencies (this should avoid caching + missing /pages directory problem)
--------------------
error: failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1```

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://handler-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://handler-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by arpargo — APPROVED** [review]
LGTM

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://handler-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://handler-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://handler-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://handler-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://handler-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe applicant result is __failed__ for https://helsinkilisa-ui-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe applicant result is __failed__ for https://helsinkilisa-ui-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe applicant result is __failed__ for https://helsinkilisa-ui-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe employer result is __failed__ for https://kesaseteli-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://handler-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://youth-pr2015.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2015.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2015.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://handler-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://youth-pr2015.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://handler-pr2015.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-pr2015.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://youth-pr2015.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
