### PR TITLE
Hl 1024 ahjo

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Remove the unnecessary diary number received ahjo status.
Prepare the Application model to  eventually receive a case id and a case guid from Ahjo.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2408.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2408.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2408.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2408.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2408.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mjturt — APPROVED** [review]

**Pull request merged**
