### PR TITLE
feat: remove decimals from alteration sum

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1490](https://helsinkisolutionoffice.atlassian.net/browse/HL-1490?atlOrigin=eyJpIjoiNmU4NGFiNTE1YTRhNDA4NTljZDgxZDc3ZTNhMGI0NWEiLCJwIjoiaiJ9)

## Screenshots :camera_flash:
image-20241001-063744
Screenshot 2024-10-12 at 11 58 56

## Additional notes :spiral_notepad:

[HL-1490]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3436.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3436.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3436.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3436.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr3436.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr3436.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr3436.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Pull request merged**
