### PR TITLE
feat: application change history (HL-1061)

### PR DESCRIPTION
**Pull request by mjturt**
## Description :sparkles:

This adds the `change` key to the application payload. `change` key is a list of change dictionaries. Change dictionaries are in format `{"field": <field>, "old": <old_value>, "new": <new_value>}`.

For the handler, the `changes` key includes changes that are made when the application status is `additional_information_needed`.

For the applicant, the `changes` key includes changes that are made by any handler to the application. To be precise, the `changes` key includes changes that are made after the application is received, excluding the possible time when the application is in the status `additional_information_needed`.

In a case of one-to-many relations (`attachments`, `de_minimis_aid_set`), the changes list includes the field with `old` and `new` values set to `None` if they are considered changed. If not, the changes list doesn't include it. Field considered changed if new objects are added or existing ones modified in the specific timeframe. So these fields can be considered special cases.

After tested thoroughly, this should be OK enough. The below-mentioned restrictions should be considered. 

## Issues :bug:

This solution is not perfect. Some notes:

- When the application is updated, de minimis aids are always all removed and then added again. This behavior messes up with change tracking and for now, tracking de minimis aids is disabled. More info in the code.
- `attachments` field considered changed only if new objects are added or existing ones modified. Removing attachments is not considered a change. Same for the `de_minimis_aids_set` if it would be enabled.
- Change history for the handler includes also changes made by the handler, if the handler modifies the application when it's in status `additional_information_needed`. I think that handlers should not edit the application in that status.
- Change history for the applicant doesn't include handler made changes when application status is `additional_information_needed`.

So, based on the above, at least editing application when status is `additional_information_needed` by handler is a bit problematic.

### Applicant change history

1. Create application as applicant
2. As a handler, add an attachment to the application (that's the only thing you can do as a handler for now)
3. Reload as applicant. Application payload `changes` key should contain attachment change.

### Handler change history

1. Create application as applicant
2. As a handler, open up the application for editing
3. As an applicant, edit the application and submit
4. Reload as a handler. The application payload `changes` key should contain the changes.

## Additional notes :spiral_notepad:

The optimal solution would be to fix the audit log. Currently, the audit log doesn't contain any changes to the related objects. Fixing the audit log would require some serious data migrations, which I unfortunately didn't have time to do.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2674.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2674.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2674.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2674.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2674.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2674.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2674.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
