### PR TITLE
YJDH-693 | feat(kesaseteli): add fallback youth summer voucher logo without price

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(kesaseteli): add fallback youth summer voucher logo without price

also:
 - add Swedish localized Helsinki logo to youth summer voucher email

refs YJDH-693

## Issues :bug:

[YJDH-693](https://helsinkisolutionoffice.atlassian.net/browse/YJDH-693)

### Youth summer voucher HTML email for year 2024 (fi/sv/en)

- voucher-2024-fi
- voucher-2024-sv
- voucher-2024-en

### Youth summer voucher HTML email with 500e price (fi/sv/en)

- voucher-500e-fi
- voucher-500e-sv
- voucher-500e-en

## Additional notes :spiral_notepad:

Youth summer voucher emails (rename to .eml from .eml.txt) files that can be opened in e.g. Outlook:
- [voucher-2024-fi.eml.txt](https://github.com/City-of-Helsinki/yjdh/files/14416729/voucher-2024-fi.eml.txt)
- [voucher-2024-sv.eml.txt](https://github.com/City-of-Helsinki/yjdh/files/14416723/voucher-2024-sv.eml.txt)
- [voucher-2024-en.eml.txt](https://github.com/City-of-Helsinki/yjdh/files/14416727/voucher-2024-en.eml.txt)
- [voucher-500e-fi.eml.txt](https://github.com/City-of-Helsinki/yjdh/files/14416725/voucher-500e-fi.eml.txt)
- [voucher-500e-sv.eml.txt](https://github.com/City-of-Helsinki/yjdh/files/14416726/voucher-500e-sv.eml.txt)
- [voucher-500e-en.eml.txt](https://github.com/City-of-Helsinki/yjdh/files/14416724/voucher-500e-en.eml.txt)

[YJDH-693]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://kesaseteli-pr2855.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EMPLOYER branch is deployed to platta: https://kesaseteli-employer-pr2855.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-employer-pr2855.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://kesaseteli-handler-pr2855.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-handler-pr2855.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://kesaseteli-youth-pr2855.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe youth result is __failed__ for https://kesaseteli-youth-pr2855.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kesaseteli-youth-pr2855.dev.hel.ninja :laughing::tada::tada::tada:

**Review by jannetalvio — APPROVED** [review]

**Pull request merged**
