### PR TITLE
YJDH-362 | Refactor summer voucher applications

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description :sparkles:

**Refactor** summer voucher and summer voucher application related classes **for clarity**:
 1. KS-Backend: Rename Application to EmployerApplication
 2. KS-Backend: Use employer_applications related_name
 3. KS-Backend: Rename SummerVoucher to EmployerSummerVoucher
 4. KS-Backend: Fix comment in get_test_phone_number
 5. KS: Prefix employer related endpoints with employer
 6. Fix styles (i.e. ran black and isort)
 7. KS-Backend: Prefix employer related serializers with Employer
 8. KS-Backend: Add employer to employer related permission names

**Rationale:**

Before in the Kesäseteli (KS) there was only Application which semantically meant EmployerApplication but was not named as such. Then YouthApplication was added and there were Application and YouthApplication. This was less than clear. Clarifying the code by renaming Application to its semantic meaning: EmployerApplication.

There was a similar situation—as in the previous paragraph—with SummerVoucher and YouthSummerVoucher. Clarifying this situation by renaming SummerVoucher to its semantic meaning: EmployerSummerVoucher.

Also doing similar renamings for other classes/endpoints that are employer specific to make that aspect explicit.

## Issues :bug:

YJDH-362

### CODE REVIEW

**Comment by karisal-anders** [comment]
`browser-test:ci` and `browser-test` pass locally:
```
frontend/kesaseteli/youth> yarn browser-test:ci
yarn run v1.22.17
$ testcafe 'chrome:headless --disable-gpu --window-size="1249,720" --ignore-certificate-errors-spki-list="8sg/cl7YabrOFqSqH+Bu0e+P27Av33gWgi8Lq28DW1I=,gJt+wt/T3afCRkxtMMSjXcl/99sgzWc2kk1c1PC9tG0=,zrQI2/1q8i2SRPmMZ1sMntIkG+lMW0legPFokDo3nrY="' --screenshots path=report,fullPage=true --video report --reporter spec,custom,html:report/index.html testcafe.dotenv.js browser-tests/
-
 Running tests in:
 - Chrome 96.0.4664.110 / Windows 10

 Frontpage
 √ can fill up youth application

 Frontpage
 √ can change to languages


 2 passed (26s)
Done in 46.63s.
frontend/kesaseteli/youth> yarn browser-test
yarn run v1.22.17
$ testcafe 'chrome --ignore-certificate-errors --ignore-urlfetcher-cert-requests --window-size="1249,720"' testcafe.dotenv.js browser-tests/
 Running tests in:
 - Chrome 96.0.4664.110 / Windows 10

 Frontpage
 √ can fill up youth application

 Frontpage
 √ can change to languages


 2 passed (30s)
Done in 60.77s.
```

**Comment by karisal-anders** [comment]
To clarify the code review requests:
 - @haavikko & @quyenlq: I requested code review mainly from you as this PR is mainly backend related. Please could one of you code review this pull request? Thank you!
 - @nenonja: I requested code review secondarily from you as this PR also includes frontend related code changes. Please could you code review the frontend related code changes in this pull request? Thank you!

**Comment by karisal-anders** [comment]
<ins>The tests pass now</ins>, they were fixed with the merging of PR #583 and rebasing on `develop` after that.

**Review by nenonja — APPROVED** [review]
frontend part looks food, and browser tests still pass so approved from my part. But it perhaps still needs backend guy also to check it.

**Review by haavikko — APPROVED** [review]
Looks good to me!
I think the commits can be squashed before merging. For reviewing it was nice to have the commits separate, though :-)

**Pull request merged**
