### PR TITLE
fix: Application status is already change to HANDLING when showing no…

### PR DESCRIPTION
**Pull request by JanneJuhola**
Application status is already change to HANDLING when showing notification. 
 Not anymore INFO_REQUIRED
 New application status is RECEIVED

### CODE REVIEW

**Review by rikuke — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3651.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3651.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3651.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
