### PR TITLE
feat: remove "Palkan" from salary benefit locale

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Shorten the salary benefit finnish translation from "Palkan Helsinki-lisä" to "Helsinki-Lisä".

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2881.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Review by JanneJuhola — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2881.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2881.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2881.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
