### PR TITLE
HL-913 | Toast had no translation for close button label

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Add missing translations.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2185.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2185.dev.hel.ninja** :rocket::rocket::rocket:

**Review by mjturt — APPROVED** [review]

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2185.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2185.dev.hel.ninja :laughing::tada::tada::tada:

**Review by JanneJuhola — APPROVED** [review]

**Pull request merged**
