### PR TITLE
HL-642 cont. | Rename conflicting migration file

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Fix conflicting migration file name issue.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2171.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2171.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2171.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2171.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mjturt — APPROVED** [review]
Damn, seems that this was my bad. Good catch :+1: :+1:

**Pull request merged**
