### PR TITLE
Hl 1283 ahjo errors

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1283](https://helsinkisolutionoffice.atlassian.net/browse/HL-1283)
Save any errors received from ahjo callbacks to the last ahjo_status, and include them in the handler's JSON.
## Screenshots :camera_flash:
Screenshot 2024-08-12 at 16 07 58

## Additional notes :spiral_notepad:

[HL-1283]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3208.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3208.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3208.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3208.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
