### PR TITLE
feat: find related applications for a single employee (hl-1354)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

Handler can now efficiently find employee's previous benefits. 

* Modify search code to use an existing application as base to find related other applications
  * List any `Application` objects with matching SSN (note that first_name and last_name can change)
  * List any `ArchivalApplication` objects by matching with best guess keys: `first_name`, `last_name` and `year_of_birth` (parsed from SSN)
* Implement button to click in application view, seek for Employee section
* Refactor and implement search view

### 🔍 View of single application's search button

---

Screenshot 2024-09-12 at 10 21 18

### 📁  View of related applications when button is clicked

---

image

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3321.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3321.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3321.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3321.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Pull request merged**
