### PR TITLE
feat: HL 1440 set archived status for applications

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL 1440](https://helsinkisolutionoffice.atlassian.net/browse/HL-1440?atlOrigin=eyJpIjoiNDc5Yjg4NzYwOWJmNDE0Mzk4OWY4MDM5MTkyNTUwZWMiLCJwIjoiaiJ9)

Update application.archived as True after it has been cancelled in ahjo or processed in Talpa.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3236.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3236.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3236.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3236.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]
Approving for now but  there's a risk of losing all the status data if talpa doesnt handle the response well.

**Pull request merged**
