### PR TITLE
YJDH-689 | fix(tests): fix autoComplete type tests

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix(tests): fix autoComplete type tests

Previously autoComplete tests failed [1] because they were compile-time
rather than run-time tests, and they were in a file that expected
run-time tests. Moved the compile-time tests to the type file instead.

[1]:
```
yarn run v1.22.21
$ cross-env TZ=Europe/Helsinki yarn test --verbose --coverage
$ cross-env TZ=Europe/Helsinki jest --verbose --coverage
FAIL src/types/tests/auto-complete.test.ts
  ● Test suite failed to run

	Your test suite must contain at least one test.

	  at onResult (../node_modules/@jest/core/build/TestScheduler.js:...
	  at ../node_modules/@jest/core/build/TestScheduler.js:316:17
	  at ../node_modules/emittery/index.js:260:13
		  at Array.map (<anonymous>)
	  at Emittery.emit (../node_modules/emittery/index.js:258:23)
```

refs YJDH-689

## Issues :bug:

- [YJDH-689](https://github.com/City-of-Helsinki/yjdh/pull/2782)

## Additional notes :spiral_notepad:

[YJDH-689]: https://helsinkisolutionoffice.atlassian.net/browse/YJDH-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://tet-pr2793.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2793.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ADMIN branch is deployed to platta: https://tet-admin-ui-pr2793.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tet-admin-ui-pr2793.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2793.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2793.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH branch is deployed to platta: https://tet-youth-ui-pr2793.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tet-youth-ui-pr2793.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr2793.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
