### PR TITLE
fix:loc key added for application.handling & .cancelled (HL-1288)

### PR DESCRIPTION
**Pull request by JanneJuhola**

### CODE REVIEW

**Review by EmiliaMakelaVincit — APPROVED** [review]

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2962.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2962.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2962.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2962.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
