### PR TITLE
feat: save missing version_series_id error

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1518](https://helsinkisolutionoffice.atlassian.net/browse/HL-1518)
If version_series_id is missing for some reason, store the error into ahjoStatus.
## Additional notes :spiral_notepad:

[HL-1518]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3641.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3641.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3641.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3641.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3641.dev.hel.ninja :laughing::tada::tada::tada:

**Review by JanneJuhola — APPROVED** [review]

**Pull request merged**
