### PR TITLE
Add missing pay subsidy migrations

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Paysubsidy percentages were changed during the calculator rules update, but the changes to the Application and Calculator model were missing the migrations.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2190.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2190.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2190.dev.hel.ninja** :rocket::rocket::rocket:

**Review by mjturt — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2190.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
