### PR TITLE
feat: secret xml attachment as per the  new design

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1207](https://helsinkisolutionoffice.atlassian.net/browse/HL-1207?atlOrigin=eyJpIjoiYWZhYmYzNjIyYWUyNDk5MzhiYjU0ZmNlZTYxMDIxYTMiLCJwIjoiaiJ9) format the secret decision XML according to the new design (see screenshots).

Refactor the XML building to a class, as ahjo_integration.py is already doing way too much stuff.
Add more tests for the XML strings.

[HL-1242](https://helsinkisolutionoffice.atlassian.net/browse/HL-1242?atlOrigin=eyJpIjoiMmFkOGRlYmVjYWIyNGIwOTljNzExNDBkZTZlMTEzMjMiLCJwIjoiaiJ9) Rename the generated XML files to format requested by AHJO.

## Testing :alembic
`pytest applications/tests/test_ahjo_xml_builder.py`
To manually check what kind of XML files are created run
`python manage.py shell_plus`
`from applications.services.ahjo_integration import generate_application_attachment`
`from applications.enums import AttachmentType`
`app = Application.objects.get(pk="some_accepted_application_id")`
`generate_application_attachment(app, AttachmentType.DECISION_TEXT_SECRET_XML)`
the xml file is then found at `/var/media `folder.
## Screenshots :camera_flash:
Screenshot 2024-03-27 at 15 35 02
Screenshot 2024-03-27 at 15 34 51

## Additional notes :spiral_notepad:

[HL-1207]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HL-1242]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2899.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2899.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2899.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2899.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2899.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr2899.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2899.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2899.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2899.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2899.dev.hel.ninja :laughing::tada::tada::tada:

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2899.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2899.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2899.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2899.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2899.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2899.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2899.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2899.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2899.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2899.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
