### PR TITLE
HL-754: Remove obsolete checkboxes

### PR DESCRIPTION
**Pull request by mjturt**
## Description :sparkles:

Removed obsolete checkboxes "kohderyhmätarkistus" and "palkkatuki myönnetty vamman tai sairauden vuoksi".

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2188.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2188.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2188.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2188.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2188.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
