### PR TITLE
feat: instalment model

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
[HL-1485](https://helsinkisolutionoffice.atlassian.net/browse/HL-1485?atlOrigin=eyJpIjoiMTg2NGY0YjhmZDI5NDg4OWE3YWFkZDNhMTNhZDI0N2YiLCJwIjoiaiJ9)

Adds Instalment model and database migration in the Calculator app namespace.

## Additional notes :spiral_notepad:

[HL-1485]: https://helsinkisolutionoffice.atlassian.net/browse/HL-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3467.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3467.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3467.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr3467.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe applicant result is __failed__ for https://helsinkilisa-ui-pr3467.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by sirtawast — APPROVED** [review]

**Pull request merged**
