### PR TITLE
fix: preselect decision maker if it was selected before (hl-1530)

### PR DESCRIPTION
**Pull request by sirtawast**
## Description :sparkles:

* chore: Deprecate `handler_role` from backend
  * remove `handler` and `handlerRole` references from frontend
* fix: decision maker validation
* fix: pre-selection of decision maker radio button if it was previously selected
* feat: add a new column to calculation review box that displays the selected decision maker
* fix: store the appropriate decision maker to proposal by fetching it from backend using the id sent from frontend request rather than just writing the request values directly into db
* chrore: remove redundant and unused file 
* fix: bug that caused application crash
  * ☠️  When writing a proposal and hit cancellation button in the action bar, then closing the modal

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3522.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3522.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3522.dev.hel.ninja :laughing::tada::tada::tada:

**Review by rikuke — APPROVED** [review]

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3522.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3522.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3522.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3522.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
