### PR TITLE
fix: defer accepted/rejected status until the decision has been accepted in Ahjo (HL-1241)

### PR DESCRIPTION
**Pull request by EmiliaMakelaVincit**
## Additional notes :spiral_notepad:
Only includes the old batch based solution as discussed. Checks for both this and for applicant-side archive status according to the new Ahjo integration will be implemented later.

### CODE REVIEW

**Review by sirtawast — APPROVED** [review]

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr2903.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2903.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2903.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2903.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
