### PR TITLE
fix: open case title limit to 150 chars

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Fix issue with open case title, limit was earlier too short, 100 chars, when actually it should have been 150.

### CODE REVIEW

**Review by JanneJuhola — APPROVED** [review]

**Comment by terovirtanen** [comment]
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3292.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3292.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3292.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3292.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3292.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
