### PR TITLE
fix: add SBOM to powerBI csv

### PR DESCRIPTION
**Pull request by rikuke**
## Description :sparkles:
Add missing SBOM character to the beginning of the CSV, so that the letters are not mangled.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**API branch is deployed to platta: https://helsinkilisa-pr3355.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3355.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3355.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3355.dev.hel.ninja :laughing::tada::tada::tada:

**Review by JanneJuhola — APPROVED** [review]

**Pull request merged**
